### ISSUE TITLE
Use with hosted mysql instance?

### ISSUE THREAD

**Issue by rfrlcode** [mattrobenolt/ps-http-sim#13]
Does anyone know how I could use this with a hosted mysql instance? Been trying to make it work, but keep getting errors (I am also not very savvy with this stuff)

**Comment by mattrobenolt** [comment]
What errors are you getting? There shouldn't be any real reason you couldn't do that. I'm not sure I'd recommend it tho. This isn't intended to be used for production use cases.

**Comment by rfrlcode** [comment]
Damn, thank you for the fast response. I think mostly I am unable to connect to the hosted instance.
Lets say for example, that the uri for my hosted instance is:
mysql://admin:password@host.a.aivencloud.com:28146/defaultdb?ssl-mode=REQUIRED

this is my docker compose yml:
version: "3.8"
services:
planetscale-proxy:
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-mysql-no-pass",
        "-listen-port=3900",
        "-mysql-dbname=defaultdb",
        "-mysql-addr=ps-/admin:password@host.a.aivencloud.com",
      ]
    ports:
      - 3900:3900
      
      when I try use http://root:unused@localhost:3900 to connect to the proxy, it refuses to connected to the hosted instance. do you think something is wrong with the yml file?

**Comment by rfrlcode** [comment]
actually, I figured it out.
this would be the yml:
services:
  planetscale-proxy:
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-listen-port=3900",
        "-mysql-dbname=dbname",
        "-mysql-addr=host.a.aivencloud.com",
        "-mysql-port=28146",
      ]
    ports:
      - 3900:3900
      
and then the connection url in the env file would be: "http://admin:password@localhost:3900"

Thanks tho!

**Comment by mattrobenolt** [comment]
Yeah, was gonna say, it seems you're missing the port. It assume 3306.

**Comment by rfrlcode** [comment]
Yup exactly. Thanks!
