### ISSUE TITLE
question: arm docker image

### ISSUE THREAD

**Issue by juliusmarminge** [mattrobenolt/ps-http-sim#14]
most likely skill issue or an issue with the new Mac beta, but I seem to get an amd build of the docker image:

![CleanShot 2024-06-12 at 16 05 06@2x](https://github.com/mattrobenolt/ps-http-sim/assets/51714798/b4dd5a4e-caef-4093-9d7c-de36c3e63c41)

![CleanShot 2024-06-12 at 16 03 43@2x](https://github.com/mattrobenolt/ps-http-sim/assets/51714798/be329e0c-8049-44f1-b921-137190cd9da4)

can't remember if this was there before I updated and that it's some Rosetta bug in the new beta, just thought I'd ask. Couldn't seem to figure out if there is one from ghcr:

https://github.com/mattrobenolt/ps-http-sim/pkgs/container/ps-http-sim

compared to something on dockerhub which specifies the arch:
![CleanShot 2024-06-12 at 16 06 45](https://github.com/mattrobenolt/ps-http-sim/assets/51714798/3cb89664-a009-4a6b-b5da-7aa72f66d529)

**Comment by juliusmarminge** [comment]
using the go binary as a workaround for now but this project we use docker compose for other stuff so would like to get it working. might have to go back to a stable Mac version xd

**Comment by mattrobenolt** [comment]
No, you're correct. I'll have to look into how to do this. :) I assume it shouldn't be hard. Thanks for letting me know. I know OrbStack will run amd64 containers on arm64 chips.

**Comment by mattrobenolt** [comment]
In theory this works. Let's see! https://github.com/mattrobenolt/ps-http-sim/commit/3833955b075dfc8d712b1cd7cac64d32106e27c4

**Comment by mattrobenolt** [comment]
Ok, I think that did the thing.

https://github.com/mattrobenolt/ps-http-sim/pkgs/container/ps-http-sim/229200920?tag=latest

Seems the v0.0.8 variants now are multi-platform.

<img width="739" alt="image" src="https://github.com/mattrobenolt/ps-http-sim/assets/375744/9e38c911-4f70-4117-ae14-e356004f8773">

And when I pull the image from my mac, I get the arm64 variant, while pulling v0.0.7 explicitly gets me the amd64 version.

**Comment by mattrobenolt** [comment]
I can confirm I also used to see that error, I have just never run this from a docker container before to notice.

```
$ docker run --rm -it ghcr.io/mattrobenolt/ps-http-sim:v0.0.7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
   2.429784ms |INFO| running HTTP server caller="ps-http-sim/main.go:274" addr="0.0.0.0" port=8080

$ docker run --rm -it ghcr.io/mattrobenolt/ps-http-sim:v0.0.8
    143.669µs |INFO| running HTTP server caller="ps-http-sim/main.go:274" addr="0.0.0.0" port=8080
```

**Comment by cdcarson** [comment]
This is working for me on an Apple M1 chip (it wasn't the last time I checked a couple of months ago, with the platform error.) Thanks man!
