### ISSUE TITLE
Error: use of closed network connection

### ISSUE THREAD

**Issue by chronark** [mattrobenolt/ps-http-sim#15]
Today I started to receive these errors very randomly and not consistently

```
read tcp 172.19.0.5:50842->172.19.0.2:3306: use of closed network connection\nio.ReadFull(header size) failed (errno 2013) (sqlstate HY000) during query: <OMITED>
```

We run both mysql and this in docker via [compose](https://github.com/unkeyed/unkey/blob/main/deployment/docker-compose.yaml)

we haven't changed anything on our end, so I'm a bit surprised this started to happen. It might be unrelated, but I wanted to ask anyways if this could be an issue coming from ps-http-sim

**Comment by mattrobenolt** [comment]
I don't particularly see how, in theory I can have more robust connection handling to reconnect and whatnot, which is fair. But I don't know why the networking would break in this setup. I have very little experience with docker in general.

**Comment by chronark** [comment]
It was a long shot, I don't see any changes here that would've caused this, not did we change anything. I've been running this docker setup for months now and running tests suites against it frequently.

If this is not coming from ps-http-sim, then we can close it this

**Comment by mattrobenolt** [comment]
Ok, I see what's going on here.

So I can reproduce this based on the `-mysql-idle-timeout` flag. The logic here is pretty naive, but this timing by default is 10 seconds.

This logic is naive in that it starts the idle timeout when it's pulled from the connection pool. The timer is also reset after every query, so in practice I think this can only get hit if the actual running query takes longer than this idle timeout.

I see in your case, you have this set to 1s: https://github.com/unkeyed/unkey/blob/main/deployment/docker-compose.yaml#L27

So any query that executes for over 1 second is going to be prematurely cut off.

Let me refactor this logic a tad so the timer is stopped while a connection is in use.

**Comment by mattrobenolt** [comment]
Wanna try out v0.0.9? https://github.com/mattrobenolt/ps-http-sim/releases/tag/v0.0.9

I assume it'll work better for you. :)
