### ISSUE TITLE
ignore certain planetscale features when proxying

### ISSUE THREAD

**Issue by juliusmarminge** [mattrobenolt/ps-http-sim#5]
Hello,

Thank you for this simulator/proxy - been looking for this for a while now!

I would like to suggest that this proxy could "ignore" certain planetscale features such as enabling boost for example. This is something I wont have on my local mysql instance so setting the variable throws an error.

For example, this is how I setup my drizzle client:

![image](https://github.com/mattrobenolt/ps-http-sim/assets/51714798/e23b636a-8732-4264-82d4-c7a38f707d18)

But running this with the proxy, I get this error:

![image](https://github.com/mattrobenolt/ps-http-sim/assets/51714798/d4939e46-c812-42ca-8ee8-3e4b56633b30)

There are workarounds I can do to fix this, for example:

```ts
const ps = connect(credentials);
(async () => {
  if (process.env.PS_PROXY) return;
  await ps.execute("SET @@boost_cached_queries = true");
})();

export const db = ...
```

But ideally I wouldn't need to write different code paths for when I'm proxying and when I'm not. I could also add the variable on my local mysql db, but that's one extra step I need to do and if you're like me and reset your local db quite often, that can be tedious and easy to forget.

So ideally the proxy could catch queries like the one above and not executing them on the local db.

**Comment by mattrobenolt** [comment]
This is pushed with v0.0.7.
